repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
  - repo: local
    hooks:
      - id: swagger-generate
        name: swagger-generate
        entry: bash -c "githooks/swagger-generate.sh"
        language: system
        verbose: true
        files: .go$
      - id: swagger-validate
        name: swagger-generate
        entry: bash -c "githooks/swagger-validate.sh"
        language: system
        verbose: true
        files: .go$
      - id: linter
        name: linter
        entry: bash -c "githooks/linter.sh"
        language: system
        verbose: true
        files: .go$
