name: Create and publish a Docker image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: ["develop"]
  release:
    types: ["published"]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract metadata (tags, label) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: "./deployments/production/Dockerfile"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - if: ${{ steps.extract_branch.outputs.branch != 'develop' }}
        name: Deploy on prod server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/diverse/Diverse-Back-prod
            git checkout main
            git pull
            sudo docker-compose stop
            sudo docker-compose -f docker-compose.yml --profile prod pull
            sudo docker-compose -f docker-compose.yml --profile prod up -d --build

      - if: ${{ steps.extract_branch.outputs.branch == 'develop' }}
        name: Deploy on test server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/diverse/Diverse-Back-test
            git checkout develop
            git pull
            sudo docker-compose stop
            sudo docker-compose -f docker-compose.yml --profile test pull
            sudo docker-compose -f docker-compose.yml --profile test up -d --build
