name: Create and publish a Docker image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: ['develop']
  release:
    types: ['published']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Log in to the registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Extract metadata (tags, label) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=mytag-{{branch}}

    - if: ${{ inputs.run_type == '' }}
      name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: "./deployments/production/Dockerfile"
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    - if: ${{ inputs.run_type != '' }}
      name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: "./deployments/production/Dockerfile"
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.run_type }}
        labels: ${{ steps.meta.outputs.labels }}