name: Go build and lint

env:
  GO_VERSION: 1.20.x

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verify dependencies
        run: go mod verify

      - name: Go modules Cache
        uses: actions/cache@v3
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - if: steps.go-cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: dependencies

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: go test -race -vet=off -v ./...

  lint:
    runs-on: ubuntu-latest
    needs: dependencies

    steps:
      - uses: actions/checkout@v3

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
